// flow-typed signature: 0beee16de0bd9d5cf78b1ec09e9d346e
// flow-typed version: <<STUB>>/next-pwa_v^5.0.5/flow_v0.144.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-pwa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-pwa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-pwa/cache' {
  declare module.exports: any;
}

declare module 'next-pwa/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-pwa/cache.js' {
  declare module.exports: $Exports<'next-pwa/cache'>;
}
declare module 'next-pwa/index' {
  declare module.exports: $Exports<'next-pwa'>;
}
declare module 'next-pwa/index.js' {
  declare module.exports: $Exports<'next-pwa'>;
}
declare module 'next-pwa/register.js' {
  declare module.exports: $Exports<'next-pwa/register'>;
}
