// flow-typed signature: 352e4317f9b4842d49015af06cbb94ca
// flow-typed version: <<STUB>>/purecss_v^2.0.5/flow_v0.144.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purecss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'purecss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'purecss/site/components/CodeBlock' {
  declare module.exports: any;
}

declare module 'purecss/site/components/Example' {
  declare module.exports: any;
}

declare module 'purecss/site/components/Footer' {
  declare module.exports: any;
}

declare module 'purecss/site/components/Header' {
  declare module.exports: any;
}

declare module 'purecss/site/components/Menu' {
  declare module.exports: any;
}

declare module 'purecss/site/components/SectionHeader' {
  declare module.exports: any;
}

declare module 'purecss/site/docusaurus.config' {
  declare module.exports: any;
}

declare module 'purecss/site/lib/pure' {
  declare module.exports: any;
}

declare module 'purecss/site/lib/utils' {
  declare module.exports: any;
}

declare module 'purecss/site/src' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/base' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/buttons' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/customize' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/extend' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/forms' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/grids' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/layouts' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/menus' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/start' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/tables' {
  declare module.exports: any;
}

declare module 'purecss/site/src/pages/tools' {
  declare module.exports: any;
}

declare module 'purecss/site/src/theme/Layout' {
  declare module.exports: any;
}

declare module 'purecss/site/static/js/grids' {
  declare module.exports: any;
}

declare module 'purecss/site/static/js/menus' {
  declare module.exports: any;
}

declare module 'purecss/site/static/js/track-downloads' {
  declare module.exports: any;
}

declare module 'purecss/site/static/js/ui' {
  declare module.exports: any;
}

declare module 'purecss/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'purecss/index' {
  declare module.exports: $Exports<'purecss'>;
}
declare module 'purecss/index.js' {
  declare module.exports: $Exports<'purecss'>;
}
declare module 'purecss/site/components/CodeBlock.js' {
  declare module.exports: $Exports<'purecss/site/components/CodeBlock'>;
}
declare module 'purecss/site/components/Example.js' {
  declare module.exports: $Exports<'purecss/site/components/Example'>;
}
declare module 'purecss/site/components/Footer.js' {
  declare module.exports: $Exports<'purecss/site/components/Footer'>;
}
declare module 'purecss/site/components/Header.js' {
  declare module.exports: $Exports<'purecss/site/components/Header'>;
}
declare module 'purecss/site/components/Menu.js' {
  declare module.exports: $Exports<'purecss/site/components/Menu'>;
}
declare module 'purecss/site/components/SectionHeader.js' {
  declare module.exports: $Exports<'purecss/site/components/SectionHeader'>;
}
declare module 'purecss/site/docusaurus.config.js' {
  declare module.exports: $Exports<'purecss/site/docusaurus.config'>;
}
declare module 'purecss/site/lib/pure.js' {
  declare module.exports: $Exports<'purecss/site/lib/pure'>;
}
declare module 'purecss/site/lib/utils.js' {
  declare module.exports: $Exports<'purecss/site/lib/utils'>;
}
declare module 'purecss/site/src/index' {
  declare module.exports: $Exports<'purecss/site/src'>;
}
declare module 'purecss/site/src/index.js' {
  declare module.exports: $Exports<'purecss/site/src'>;
}
declare module 'purecss/site/src/pages/base/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/base'>;
}
declare module 'purecss/site/src/pages/base/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/base'>;
}
declare module 'purecss/site/src/pages/buttons/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/buttons'>;
}
declare module 'purecss/site/src/pages/buttons/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/buttons'>;
}
declare module 'purecss/site/src/pages/customize/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/customize'>;
}
declare module 'purecss/site/src/pages/customize/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/customize'>;
}
declare module 'purecss/site/src/pages/extend/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/extend'>;
}
declare module 'purecss/site/src/pages/extend/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/extend'>;
}
declare module 'purecss/site/src/pages/forms/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/forms'>;
}
declare module 'purecss/site/src/pages/forms/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/forms'>;
}
declare module 'purecss/site/src/pages/grids/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/grids'>;
}
declare module 'purecss/site/src/pages/grids/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/grids'>;
}
declare module 'purecss/site/src/pages/index' {
  declare module.exports: $Exports<'purecss/site/src/pages'>;
}
declare module 'purecss/site/src/pages/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages'>;
}
declare module 'purecss/site/src/pages/layouts/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/layouts'>;
}
declare module 'purecss/site/src/pages/layouts/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/layouts'>;
}
declare module 'purecss/site/src/pages/menus/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/menus'>;
}
declare module 'purecss/site/src/pages/menus/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/menus'>;
}
declare module 'purecss/site/src/pages/start/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/start'>;
}
declare module 'purecss/site/src/pages/start/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/start'>;
}
declare module 'purecss/site/src/pages/tables/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/tables'>;
}
declare module 'purecss/site/src/pages/tables/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/tables'>;
}
declare module 'purecss/site/src/pages/tools/index' {
  declare module.exports: $Exports<'purecss/site/src/pages/tools'>;
}
declare module 'purecss/site/src/pages/tools/index.js' {
  declare module.exports: $Exports<'purecss/site/src/pages/tools'>;
}
declare module 'purecss/site/src/theme/Layout.js' {
  declare module.exports: $Exports<'purecss/site/src/theme/Layout'>;
}
declare module 'purecss/site/static/js/grids.js' {
  declare module.exports: $Exports<'purecss/site/static/js/grids'>;
}
declare module 'purecss/site/static/js/menus.js' {
  declare module.exports: $Exports<'purecss/site/static/js/menus'>;
}
declare module 'purecss/site/static/js/track-downloads.js' {
  declare module.exports: $Exports<'purecss/site/static/js/track-downloads'>;
}
declare module 'purecss/site/static/js/ui.js' {
  declare module.exports: $Exports<'purecss/site/static/js/ui'>;
}
declare module 'purecss/test/index' {
  declare module.exports: $Exports<'purecss/test'>;
}
declare module 'purecss/test/index.js' {
  declare module.exports: $Exports<'purecss/test'>;
}
